FROM cyberdojofoundation/go:f67b58f
LABEL maintainer=jon@jaggersoft.com
LABEL maintainer=john@reese.dev

RUN apk add build-base
ENV GO111MODULE=auto
RUN go get github.com/stretchr/testify

COPY red_amber_green.rb /usr/local/bin
