FROM ghcr.io/cyber-dojo-languages/go:34387ac
LABEL maintainer=jon@jaggersoft.com
LABEL maintainer=john@reese.dev

RUN apk add build-base

RUN go mod init cdl-go-testify
RUN go get github.com/stretchr/testify
RUN go mod download all


COPY red_amber_green.rb /usr/local/bin

