FROM ghcr.io/cyber-dojo-languages/go:34387ac
LABEL maintainer=jon@jaggersoft.com
LABEL maintainer=john@reese.dev

RUN apk add build-base
ENV GO111MODULE=auto

COPY install.sh .
RUN ./install.sh && rm ./install.sh


COPY red_amber_green.rb /usr/local/bin

